# -*- coding: utf-8 -*-
"""s&p_stock trade by season- 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GmZiMOWsH-b-tO2rwzj92wjRlFmy8ikm
"""

# Import libraries
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import datetime as dt
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Import data file and assign to variable
data = pd.read_csv('/content/cs-1.csv', parse_dates=['date'])

# Show all column names within dataset
data.columns

# Start of data set
data.head()

# Describe the data by column
data.describe().T

# Sum NaN values per column within dataset
data.isnull().sum()

# Clean data set and ignore any rows with NaN value
data = data.dropna(how='any')
print(f"Shape of dataset is {data.shape}")

# Good to have an idea of the date range
print(f"First recorded date: {data['date'].min()}")
print(f"Last recorded date: {data['date'].max()}")

"""# What season of the year is the best time to trade?

We will look at the data to see if there is a best time of year to trade, and if so, what time of year or season is this in. Since the data set is for American based firms listed on the New York stock exchange, we will look at the time of year and season from the northern hemisphere perspective:

* Spring from March 20th to June 20th
* Summer from June 21st to September 23rd
* Autumn from September 24th to December 22nd
* And Winter from December 23rd to March 19th.


This question can be answered by looking at a few factors that we can assess by the dataset. For instance; volatility. If there are a large amount of shares being bought on one stock on a certain day, then the stock exchange will represent growth and vice versa if there are a lot of sells acorss all stocks. Let's take a look at the average traded volume per year, month, week and day.
"""

year_data = data.set_index('date').groupby(pd.Grouper(freq='Y'))
year_data = year_data['volume'].mean().plot(kind='bar')
year_data.set_xticklabels(('2013', '2014', '2015', '2016', '2017', '2018'))
year_data.set_ylabel('Average Volume')
year_data.set_xlabel('Year')
year_data.set_title('Average Volume traded per year')
plt.show()

#Retreiving the mean volume group by the month
avg_permonth = data.set_index('date').groupby(pd.Grouper(freq='M'))
avg_permonth = avg_permonth['volume'].mean()

# Plot to show mean of volume per month of year
fig, axs = plt.subplots(3, 2, figsize=(12, 12))
for i, (year, sg) in enumerate(avg_permonth.groupby(avg_permonth.index.year)):
    sg.plot(ax=axs[i//2, i%2])
    
fig.suptitle('Average volume traded per month of the year', fontsize=12)
fig.tight_layout()
fig.subplots_adjust(top=0.95)
plt.show()

"""Apart from 2015, August seems to be the time where the volume seems to be at its lowest amount. This is in mid summer, not the beggining or right at the end of it. Why would the first 8 months of the year go south for the general market? And what is it about August that creates a rebound? Does this cycle throughout each year?"""

# Average volume per day
avg_perday = data.set_index('date').groupby(pd.Grouper(freq='d'))
avg_perday['volume'].mean().plot(figsize=(15, 7))

# Average volume per week
avg_perweek = data.set_index('date').groupby(pd.Grouper(freq='w'))
avg_perweek['volume'].mean().plot(figsize=(15, 7))

# Average volume per month
avg_permonth = data.set_index('date').groupby(pd.Grouper(freq='m'))
avg_permonth['volume'].mean().plot(figsize=(15, 7))

plt.legend(('Daily mean', 'Weekly mean', 'Monthly mean'))
plt.title('Daily, Weekly, Monthly mean volume throughout data')
plt.xlabel('Date')
plt.ylabel('Volume')

plt.show()

"""At the end of each year there are huge drops in volume for the NYSE's listed companies and right after the turn of each new year, there are high spikes in the volume.

Drops at the end of each year could be because:

* Majority of traders not taking risk because of less free cash due to festive season.
* Experienced traders waiting for stock to go cheaper to buy larger bulk quantity

And spikes could potentially be due to:

* Fund allocation due to asset managers decision making for the company funds per year
* Private investors gaining bonuses per year and have more to risk
* Retailers reporting profits taken from festive season

If we assume that private investors and asset managers buy stock in late December or early January then we can assume that the best time of year to buy stock as a private investor would be the same time. As a private investor you could ride the wave of buying cheap and selling high. You would just need to find the right stock to buy!

## Apple vs. Microsoft

By comparing Apple and Microsoft we're looking at the two biggest tech stocks on the market (most popular anyway, not by market share. I don't know the market share of these companies!). Analysing these two stocks and comparing against each other by opening and closing prices, high and low price, we can judge what would've been a great day to buy these two particular shares.
"""

# Apple 5 year history
dataAAPL = data.loc[data.Name=='AAPL', :]
dataAAPL

# Amazon 5 year history
dataMSFT = data.loc[data.Name=='MSFT', :]
dataMSFT

fig, axes = plt.subplots(1, 2, figsize=(20, 5))

# Apple graph
plt.subplot(121)
plt.plot(dataAAPL['date'], dataAAPL['open'])
plt.plot(dataAAPL['date'], dataAAPL['close'])
plt.title('Apple opening and closing prices')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend(('Open', 'Close'), loc='upper left')
plt.grid(True)

# Microsoft graph
plt.subplot(122)
plt.plot(dataMSFT['date'], dataMSFT['open'])
plt.plot(dataMSFT['date'], dataMSFT['close'])
plt.title('Microsoft opening and closing prices')
plt.xlabel('Date')
plt.ylabel('Price')
plt.grid(True)
plt.legend(('Open', 'Close'), loc='upper left')


plt.show()

"""We can see that there is not much difference between the opening and closing prices for these two shares.The best points on the graph would be the lowest opening price and highest closing price. For Apple you can see just over the mid point of 2015 to 2016 the opening price was much lower than the closing price. For Microsoft there's not much visible opportunity for day trading. Long term holding though would have given a large return."""

fig, axes = plt.subplots(1, 2, figsize=(20, 5))

# Opening prices
plt.subplot(121)
plt.plot(dataAAPL['date'], dataAAPL['open'], '--b')
plt.plot(dataMSFT['date'], dataMSFT['open'], ':r')
plt.title('Opening prices')
plt.xlabel('Date')
plt.ylabel('Price')
plt.legend(('AAPL', 'MSFT'), loc='upper left')
plt.grid(True)

# Closing prices
plt.subplot(122)
plt.plot(dataAAPL['date'], dataAAPL['close'], '--b')
plt.plot(dataMSFT['date'], dataMSFT['close'], ':r')
plt.title('Closing prices')
plt.xlabel('Date')
plt.ylabel('Price')
plt.grid(True)
plt.legend(('AAPL', 'MSFT'), loc='upper left')


plt.show()

"""Apple has a larger share price which would bring back a larger profit if it was invested by bulk at specific times. However there is the risk of losing much more too."""

df1 = dataAAPL.set_index('date').loc[:, ['low']]
df2 = dataAAPL.set_index('date').loc[:, ['close']]
df3 = dataMSFT.set_index('date').loc[:, ['low']]
df4 = dataMSFT.set_index('date').loc[:, ['close']]

fig, axes = plt.subplots(1, 2, figsize=(20, 5))

plt.subplot(121)
plt.plot(df1.groupby(pd.Grouper(freq='w')).mean())
plt.plot(df2.groupby(pd.Grouper(freq='w')).mean())
plt.grid(True)
plt.legend(('Low', 'Close'))
plt.title('AAPL weekly mean of low and closing price')
plt.xlabel('Date')
plt.ylabel('Price')

plt.subplot(122)
plt.plot(df3.groupby(pd.Grouper(freq='w')).mean())
plt.plot(df4.groupby(pd.Grouper(freq='w')).mean())
plt.grid(True)
plt.legend(('Low', 'Close'))
plt.title('MSFT weekly mean of low and closing price')
plt.xlabel('Date')
plt.ylabel('Price')

plt.show()

df1 = dataAAPL.set_index('date').loc[:, ['high']]
df2 = dataAAPL.set_index('date').loc[:, ['open']]
df3 = dataMSFT.set_index('date').loc[:, ['high']]
df4 = dataMSFT.set_index('date').loc[:, ['open']]

fig, axes = plt.subplots(1, 2, figsize=(20, 5))

plt.subplot(121)
plt.plot(df1.groupby(pd.Grouper(freq='w')).mean())
plt.plot(df2.groupby(pd.Grouper(freq='w')).mean())
plt.grid(True)
plt.legend(('High', 'Open'))
plt.title('AAPL weekly mean of high and opening price')
plt.xlabel('Date')
plt.ylabel('Price')

plt.subplot(122)
plt.plot(df3.groupby(pd.Grouper(freq='w')).mean())
plt.plot(df4.groupby(pd.Grouper(freq='w')).mean())
plt.grid(True)
plt.legend(('High', 'Open'))
plt.title('MSFT weekly mean of high and opening price')
plt.xlabel('Date')
plt.ylabel('Price')

plt.show()

df1 = dataAAPL.set_index('date').loc[:, ['high']]
df2 = dataAAPL.set_index('date').loc[:, ['low']]
df3 = dataMSFT.set_index('date').loc[:, ['high']]
df4 = dataMSFT.set_index('date').loc[:, ['low']]

fig, axes = plt.subplots(1, 2, figsize=(20, 5))

plt.subplot(121)
plt.plot(df1.groupby(pd.Grouper(freq='w')).mean())
plt.plot(df2.groupby(pd.Grouper(freq='w')).mean())
plt.grid(True)
plt.legend(('High', 'Low'))
plt.title('AAPL weekly mean of high and Low price')
plt.xlabel('Date')
plt.ylabel('Price')

plt.subplot(122)
plt.plot(df3.groupby(pd.Grouper(freq='w')).mean())
plt.plot(df4.groupby(pd.Grouper(freq='w')).mean())
plt.grid(True)
plt.legend(('High', 'Low'))
plt.title('MSFT weekly mean of high and low price')
plt.xlabel('Date')
plt.ylabel('Price')

plt.show()

sns.pairplot(dataAAPL, x_vars=['open', 'high', 'low', 'close'], y_vars=['volume'], height=10, kind='reg')

"""As we can see by using seaborns pairplot, there are groups of different trades by opening price vs volume. There are gaps between such points also which may indicate a wary market. It seems the higher the volume the lower the opening price and higher the opening price the lower the volume. This is of course an obvious thing, the higher something costs the less you can have of it."""

sns.pairplot(dataMSFT, x_vars=['open', 'high', 'low', 'close'], y_vars=['volume'], height=10, kind='reg')

"""Microsofts scatter points don't seem as spread out as Apple's. They all seem to cluster together with what I would assume between the 40-50 range of each graph being an area where volume traded has clustered.

### Scatter plots of Apple in 2015 and 2016
"""

aapl_2015 = dataAAPL.set_index('date')
aapl_2015 = aapl_2015.loc['2015-01':'2015-12']

sns.pairplot(aapl_2015, x_vars=['open', 'high', 'low', 'close'], y_vars=['volume'], height=10, kind='reg')

input = 125
print(dataAAPL.iloc[(dataAAPL['open']-input).abs().argsort()[:2]])
print(dataAAPL.iloc[(dataAAPL['high']-input).abs().argsort()[:2]])
print(dataAAPL.iloc[(dataAAPL['low']-input).abs().argsort()[:2]])
print(dataAAPL.iloc[(dataAAPL['close']-input).abs().argsort()[:2]])

"""So for the grouping on the scatter diagrams for the columns against volume, the dates range from earliest as February to latest July. This is where a large grouping of scatter points are on each diagram."""

aapl_2016 = dataAAPL.set_index('date')
aapl_2016 = aapl_2016.loc['2016-01':'2016-12']

sns.pairplot(aapl_2016, x_vars=['open', 'high', 'low', 'close'], y_vars=['volume'], height=10, kind='reg')

input = 110
print(dataAAPL.iloc[(dataAAPL['open']-input).abs().argsort()[:2]])
print(dataAAPL.iloc[(dataAAPL['high']-input).abs().argsort()[:2]])
print(dataAAPL.iloc[(dataAAPL['low']-input).abs().argsort()[:2]])
print(dataAAPL.iloc[(dataAAPL['close']-input).abs().argsort()[:2]])

"""### Scatter plots of Microsoft in 2015"""

msft_2015 = dataMSFT.set_index('date')
msft_2015 = msft_2015.loc['2015-01':'2015-12']

sns.pairplot(msft_2015, x_vars=['open', 'close', 'low', 'high'], y_vars=['volume'], height=10, kind='reg')

input = 47
print(dataMSFT.iloc[(dataAAPL['open']-input).abs().argsort()[:2]])
print(dataMSFT.iloc[(dataAAPL['high']-input).abs().argsort()[:2]])
print(dataMSFT.iloc[(dataAAPL['low']-input).abs().argsort()[:2]])
print(dataMSFT.iloc[(dataAAPL['close']-input).abs().argsort()[:2]])

msft_2016 = dataMSFT.set_index('date')
msft_2016 = dataMSFT.loc['2015-01':'2015-12']

sns.pairplot(msft_2016, x_vars=['open', 'close', 'low', 'high'], y_vars=['volume'], height=10, kind='reg')

input = 47
print(dataMSFT.iloc[(dataAAPL['open']-input).abs().argsort()[:2]])
print(dataMSFT.iloc[(dataAAPL['high']-input).abs().argsort()[:2]])
print(dataMSFT.iloc[(dataAAPL['low']-input).abs().argsort()[:2]])
print(dataMSFT.iloc[(dataAAPL['close']-input).abs().argsort()[:2]])

"""## Machine learning forecasting on Apple stock"""

x = dataAAPL[['open', 'low', 'high']]
y = dataAAPL['close']

X_train, X_test, y_train, y_test = train_test_split(x, y, random_state=1)

print(len(X_train))
print(len(X_test))
print(len(y_train))
print(len(y_test))
print(f"Total records : {len(X_train) + len(X_test)}")

"""### Linear regression model"""

linreg = LinearRegression()
linreg.fit(X_train, y_train)

print(round(linreg.intercept_, 3))
print(linreg.coef_)

linreg.predict(X_test)

round(linreg.score(X_test, y_test)*100, 3)